# Gate.io API 配置文件
# Gate.io API 配置文件

# 服务器配置
Server:
  port: 8080

# 交易对列表，包含最大预期价格和最低预期价格
pairs:
  - symbol: XX_USDT
    max_price: 1
    min_price: 0.1
  - symbol: XX_USDT_USDT
    max_price: 1
    min_price: 0.1
# 恐慌指标值
FearGreed: 56

# CoinMarketCap API 配置
CoinMarketCap:
  apiKey: 

# Telegram 配置
Telegram:
  botToken: 
  chatID: 
  chatID: 
