# Gate.io API 配置文件

# 交易对列表，包含最大预期价格和最低预期价格
pairs:
  - symbol: BLD_USDT
    max_price: 0.0095
    min_price: 0.0085
  - symbol: AKT_USDT
    max_price: 2.0
    min_price: 1.0

Telegram:
  botToken: "7734102794:AAGD7ZEwCoD6sFde8T7c6nNmfn7wy4Q1wCI"
  chatID: "7691276994"